import subprocess

subprocess.check_call(["python","Experiments/Ex1_1.py"])
subprocess.check_call(["python","Experiments/Ex1_2.py"])
subprocess.check_call(["python","Experiments/Ex1_3.py"])
subprocess.check_call(["python","Experiments/Ex1_4.py"])
subprocess.check_call(["python","Experiments/Ex1_5.py"])
subprocess.check_call(["python","Experiments/Ex1_6.py"])
subprocess.check_call(["python","Experiments/Ex1_7.py"])
subprocess.check_call(["python","Experiments/Ex2_1.py"])
subprocess.check_call(["python","Experiments/Ex2_3.py"])
subprocess.check_call(["python","Experiments/Ex2_3.py"])
subprocess.check_call(["python","Experiments/Ex2_4.py"])
subprocess.check_call(["python","Experiments/Ex2_5.py"])
subprocess.check_call(["python","Experiments/Ex2_6.py"])
subprocess.check_call(["python","Experiments/Ex2_7.py"])
subprocess.check_call(["python","Experiments/Ex3_1.py"])
subprocess.check_call(["python","Experiments/Ex3_2.py"])
subprocess.check_call(["python","Experiments/Ex3_3.py"])
subprocess.check_call(["python","Experiments/Ex3_4.py"])
subprocess.check_call(["python","Experiments/Ex3_5.py"])
subprocess.check_call(["python","Experiments/Ex3_6.py"])
subprocess.check_call(["python","Experiments/Ex3_7.py"])

